version: "3"
services:
  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  app:
    container_name: webapp
    restart: always
    build: .
    volumes:
      - .:/data602A2
    ports:
      - "5000:5000"
    depends_on:
      - mongo
